### ISSUE TITLE
First Person Camera

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#13]
## First Person Camera

_See Issue #4_

We're interested in a first-person, close-to-the-ground camera that feels like a roughly human-scale entity walking around. This camera should have a few different features.

### Features

- [ ] Camera positioned close to the ground
- [ ] Camera is fixed to the ground plane / height map.
- [ ] Camera exhibits shake, bob, walking dynamics
- [ ] Camera has human-like vision / is slightly out of focus at long distances (?)

**Comment by federicoperezvilloro** [comment]
We should also consider what behaviours we want to program to these characters. And how controllable are they are. 

For instance, are we imagining a character could move on a 360 plane or are paths restricted to the course of the river?

How much of a person they are? Can they jump? 

My inclination is to keep it a bit less "embodied" that that. Think of it less as a videogame character and more as a camera that provides access into the landscapes. Not sure if this contradicts the features listed above where the camera exhibits shakes and walking dynamics... might be something we might want to test? We should strike a balance in terms of tone and where to put emphasis: I wouldn't want these details to become distracting of the larger objective the piece has: showing that the river moves, it evolves at geological scales.

**Comment by nicschumann** [comment]
Sounds good. For the first person character, let's start by simply clamping the character to the ground plane, and setting it's height to an appropriately human scale, and see how that feels. (When I play with the unconstrained 3D camera, it feels very artificial, but maybe just bringing it into an appropriate scale, height, and focal-length is enough.)

**Comment by nicschumann** [comment]
Closing this Issue. Sub issues are continued in

- #18
- #17 
- #16
