### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#24]
Write the project description, credits, and any instructions that we want to share with viewers. This will be viewable from the `info` button on the landscape view.

_We should assume that people won't click on this though, so it should totally be usable without clicking on it!_

**Comment by federicoperezvilloro** [comment]
Here's a draft of the content for the info panel: 

https://docs.google.com/document/d/1MT9xBzZL5NOcb8aJxzJNgZvGKzTZazbUlHbsI_-5BLw/edit?usp=sharing

We can certainly adjust the language together and based on the website's end result.

**Comment by nicschumann** [comment]
Closed by #47.
