### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#25]
We should figure out what the domain name for this project is, buy it, and link it to `vercel`, so we have a really shareable link.

**Comment by federicoperezvilloro** [comment]
I bought todoslosriosposibles.com as a domain name for the project. Please let me know what information you need (DNS, etc) to point the site to the url or if you want me to send you the domain credentials?

**Comment by nicschumann** [comment]
This is wired up to the production domain now. Will close this after our meeting.
