### ISSUE TITLE
Parameters Glossary

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#27]
In Sim Tools view, we should add a glossary of terms for the various parameters you can tweak, and an explanation of how they might affect the sim. Of course, this can't be _too_ direct, but it can give a poetic hint at what might happen...

**Comment by nicschumann** [comment]
For notes on the parameters, see [this document](https://docs.google.com/document/d/1iB5RIkZLDeMv-5rSvzoV2wJ_OsHZMr0B6UDHJGvZYRQ/edit).

**Comment by federicoperezvilloro** [comment]
Yes. We probably need to make a decision on which parameters will indeed make it into the interface and are legible enough for a regular user. 

Once we make that decision we can simplify the language from the document. This is something I honestly feel unequipped to do and maybe we should also get support from Lukas? Seems to me like a language task: how to breakdown / communicate what the model is simulating for the general public?

**Comment by nicschumann** [comment]
Closed by #47
