### ISSUE TITLE
Parameters Color Keys

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#28]
Different tools have different colors associated with them. Primarily, these are:

- Erosion/Accretion View
  - 9 colors, one for each type of erosion/accretion zone. Check page 20 of this document for a [description of these](https://docs.google.com/document/d/12PQ0wF_xWlWM-RUFgz8H5vhUfOcaQMElsj9E-nqdxzM/edit#heading=h.12l4jsbmhmhp). 
- Water Height View
  - There are maybe 6 different colors showing different water heights. There's probably a better way to render this though – to be investigated in a future scope.
- Curvature View
  - This has two colors, one which represents an inner back (curving towards the point we're at) and one representing an outer back (curving away from the point we're at).

**Comment by federicoperezvilloro** [comment]
I would love to propose color pallets for these but before that it would be good to:

- [ ] See further graphic explorations to distinguish between the "tools view" from the "landscape view". Hard to anticipate how you're imagining such rendering distinctions and thus how the colors might interact in context with the "land".
- [ ] 
- [ ] Get a sense of what these colors represent, if that can be described somehow. I can't seem to find a clear description of these on the document you mention on your comment above.

**Comment by nicschumann** [comment]
We are removing these views in things that are user-visible. They'll still be available in a `debug` view that I can toggle on but will not show up in the piece. We'll discuss more, but this is no longer relevant. Closing.
