### ISSUE TITLE
Final DEMs

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#29]
We need to get a final list of DEMs for the 10/19 milestone. 

@federicoperezvilloro – Please use [USGIS Lidar Explorer](https://apps.nationalmap.gov/lidar-explorer/#/) to select areas where:
- DEMs Exist
- The region of interest is fully covered in a single DEM

This will make the process of pre-processing DEMs MUCH easier. 

We can get on a call, and I can show you how to use lidar explorer, if you like.

**Comment by federicoperezvilloro** [comment]
Happy to collect these, but it would indeed be really helpful to get on a call and get a bit of a demo. I tried following the video you sent of the DEM processing, but I can seem to activate the "Show where Lidar is available" or the "Show where DEMs exist?" check boxes to move to the next steps on the USGS explorer. Let's coordinate a call. 

Here's the map with locations for future reference: https://www.google.com/maps/d/u/0/edit?mid=1CCYS0Dn_6M2PsTqoLxEdDcTKyhvxUII&usp=sharing

**Comment by nicschumann** [comment]
Hey Fede, in lieu of a call for the mean-time, [here's a video walkthrough of using the LIDAR explorer to find areas that will work for our process](https://www.loom.com/share/607afd769f814542bb60259274f6e15b). Hopefully this helps until we can find a time to sync.

**Comment by federicoperezvilloro** [comment]
Here's the map with the final locations selected

https://docs.google.com/document/d/1WH8dQ9gEocbEmvxlkWv-diucmKTP4y4grOVAL4Wm3gI/edit?usp=sharing

Also, pls refer back to my email on Oct 3rd regarding this doc.

**Comment by nicschumann** [comment]
This looks good, overall. We've already gotten a few of the rivers on the final list, too, I think. 

All river sections need to be at the same scale, and the same overall area (1.8 km^2, the maximum resolution our simulator can handle right now). I will crop out regions that cover the areas you've selected as best I can – in some cases the regions may be bigger or smaller than the rectangles you've drawn, however.

A point of note: having other bodies of water, like lakes, hitting the boundary of the simulation area is kind of an unknown condition. In simulations like this, one of the most critical parts of achieving stability is the so-called `boundary condition` – what happens when the thing being simulated hits the edge of the domain. These are very subtle, and can be the difference between a working and broken sim. We have boundary conditions that Lukas and I calibrated for the river - inflow and outflow conditions - but we do not have any for lakes, or still bodies of water hitting a boundary. I will try to render these areas with lakes as you've indicated, but be warned that they may fail.

Do you want to get rid of the rivers I already prepared? This would be a shame, as a lot of work went into preparing these, and it's not clear to me why they don't fit. 

Thanks!

**Comment by nicschumann** [comment]
hey @federicoperezvilloro, I'm finding that a lot of the links in the final DEMs document do not link to DEMs that have the features in the associated screenshots you took. A few things we could do:

1. I could correct all the links, and find DEMs that match what you have screenshoted. This will take a lot of time, and prevent me from working on other issues we have.
2. I could use simply use the links you've pasted in, and find other, similar interesting features in the dems you've linked. I don't know if this is viable, since I don't know how you're making decisions about which areas are interesting and which aren't.
3. You could update the links to correctly point to the DEMs you want, and in the meantime, I can continue working on other things, like UI and behavior.

Please let me know what you want to do! Thanks.

**Comment by federicoperezvilloro** [comment]
Nic, I took a pass on the DEM's and left additional links and comments on [the doc](https://docs.google.com/document/d/1WH8dQ9gEocbEmvxlkWv-diucmKTP4y4grOVAL4Wm3gI/edit?usp=sharing). I hope I covered all your notes and concerns, but let me know if otherwise. (I might not be looking in the right place for the 1M DEM files, yet I followed your indications on the loom video.)

**Comment by nicschumann** [comment]
Stuff to Do

- [ ] Replace names with lat-long in the `url`
