### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#35]
We need a favicon to represent the project and display in the browser tab.

**Comment by nicschumann** [comment]
@federicoperezvilloro  we still need an icon to display in the browser.

![Image](https://github.com/nicschumann/many-rivers/assets/4285161/ce42129a-f87d-4ef9-b93e-4c4a631bcec2)

What you see here is the default `favicon` for the UI framework we're using.

**Comment by federicoperezvilloro** [comment]
Let's just do a blue circle in one of the brightest shades we're using to color water. 



![Image](https://github.com/nicschumann/many-rivers/assets/22733506/3150454d-6dec-4196-8002-ff08653e2a1c)

**Comment by nicschumann** [comment]
This is closed with #48
