### ISSUE TITLE
Develop UI, Round 2

### ISSUE THREAD

**Issue by federicoperezvilloro** [nicschumann/many-rivers#39]
I'm leaving here a new, more refined, draft of an interface design. It can be further refined in the future if we do involved an additional person to work on this specifically, but for now (and for our Nov deadline) we can follow this design. 

Leaving [here a PDF](https://drive.google.com/file/d/19x_8bL7ZEaAtGa5oGBpBhbDjaErQBX35/view?usp=sharing) with notes (see second half of the doc) and [here a link](https://drive.google.com/file/d/1aR9zfWbSsjRLqHeFuIsIXc8VeNsLaJGt/view?usp=sharing) to the illustrator file.

**Comment by nicschumann** [comment]
Thanks! Questions:

### Page 1: Home
- Do we want any identifying characteristics of the river, other than the GPS coordinates of the center? A name, either real or poetic, for example?
- I will likely experiment with the rendering of the dots at the top. They read as a carousel-type image slider to me, which seems incorrect. They also position each reach of the river as disconnected, which (I assume) is not what we want. I may try something slightly different here, within the same design language.
- Not sure about the `RIVER` label. Not super clear what that is from the text.

### Page 2: Info
- Info looks good.
- This is adding more work, but should we have a version en Español at some point?

### Page 3: Tools
- The tools definitely feel overwhelming. I wonder if there's just a single overlay that we surface. I need to think more about what that would be.
- If we stay with these color coded cells, I like the idea of being able to toggle into a top-down view, and back to 3D view. That's nice.
- Regardless of what we end up showing for the tools view, I think the glossary makes sense.

### "Debug" View
- I think there's stuff on the website still that is more appropriate for "debugging" – in other words, for me – than for the user. the `PAUSE` button may fit in to this. I still need it to exist for my work, but we can hide it in every-day interaction.

### Camera
- There's nothing in here about having a free-look camera. Are we getting rid of this (fine by me)? 
- If we want to pointer-lock the mouse at any point to enable a free-look camera, we MUST have a button people press. Browsers will not allow the pointer to be locked without one – that's just built in.

### Metadata
- Agreed that time is not a good thing to show. We only have an abstract notion of things moving forward, not a convenient scale to measure on.
- I like having a spatial scale indicated, and will play with that.
- GPS coordinates make sense and are easy to add.
- We can definitely add a count of wet vs. dry cells, if we want. I currently have the total volume of water in the river segment indicated, in `m^3`.

**Comment by nicschumann** [comment]
Great, all this sounds good to me. Only a few additional points for further conversation here:

- **Naming**: The only consideration here is around the slug that shows up in the URL. Each river has its own URL right now `/rivers/[slug]` right now. If we want, we can replace this with something like `/rivers/[lat]-[long]` for example, or a random-ish number. Otherwise, we'll need some way to come up with a name or identifier.
- **Metadata**: Dry/wet count for metadata sounds great.

**Comment by nicschumann** [comment]
Here's the latest PDF from @federicoperezvilloro: [interface_design_231122_low.pdf](https://github.com/nicschumann/many-rivers/files/13454314/interface_design_231122_low.pdf)

**Comment by nicschumann** [comment]
Closed by #47
