### ISSUE TITLE
Web Archive

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#9]
## Web Archive

We're exploring the idea of archiving user-generated rivers. Essentially, this would mean saving the state of the simulator as the river evolved to some external storage medium, and building a sensible interface around this storage.

1. How do people interact with this storage / how does it plug into the rest of the web narrative?
2. How much does this cost over time?
3. When should a river be archived?

**Comment by federicoperezvilloro** [comment]
@nicschumann I think we should only archive rivers if the difference among them becomes significant or unexpected. I wonder what the purpose of collecting singular versions of the river would be if the simulator is already performing such potential for variations. The archive in comparison feels futile, even if we amass hundreds or thousands of versions of the river it will never contain as many versions as the simulator can produce. With that in mind I wonder if collecting these experiences might feel backwards, like a static version of a more dynamic map — which is the program itself.

**Comment by nicschumann** [comment]
We're not doing this as part of this push. Closing.
